### ISSUE TITLE
Разработка решения

### ISSUE THREAD

**Issue by EugeneHad** [EugeneHad/Lab1#2]
### Разработать программу, осуществляющую поиск равновесия по Нэшу в смешанных стратегиях
- [x] Разработка интерфейса приложения
- [x] Разработка логики

### Интерфейс приложения 
Представляет собой матрицу, с возможностью заносить туда данные. Кнопку - "Найти равновесие по Нэшу". И блок вывода найденного равновесия. 

### Входные данные
Необходимо заполнить таблицу 2х2, представляющую собой модель игры. Элемент таблицы - строка, содержащая два числовых значения, разделенных специальным символом.

### Выходные данные 
Представляют собой смешенные стратегии двух игроков, при которых наступает равновесие по Нэшу.

**Comment by kirinskiy2014** [comment]
Разработка приложения завершена
